// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: api.proto

package go_play

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoPlayClient is the client API for GoPlay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoPlayClient interface {
	GetResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type goPlayClient struct {
	cc grpc.ClientConnInterface
}

func NewGoPlayClient(cc grpc.ClientConnInterface) GoPlayClient {
	return &goPlayClient{cc}
}

func (c *goPlayClient) GetResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go_play.GoPlay/GetResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoPlayServer is the server API for GoPlay service.
// All implementations must embed UnimplementedGoPlayServer
// for forward compatibility
type GoPlayServer interface {
	GetResponse(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGoPlayServer()
}

// UnimplementedGoPlayServer must be embedded to have forward compatible implementations.
type UnimplementedGoPlayServer struct {
}

func (UnimplementedGoPlayServer) GetResponse(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResponse not implemented")
}
func (UnimplementedGoPlayServer) mustEmbedUnimplementedGoPlayServer() {}

// UnsafeGoPlayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoPlayServer will
// result in compilation errors.
type UnsafeGoPlayServer interface {
	mustEmbedUnimplementedGoPlayServer()
}

func RegisterGoPlayServer(s grpc.ServiceRegistrar, srv GoPlayServer) {
	s.RegisterService(&GoPlay_ServiceDesc, srv)
}

func _GoPlay_GetResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPlayServer).GetResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_play.GoPlay/GetResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPlayServer).GetResponse(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GoPlay_ServiceDesc is the grpc.ServiceDesc for GoPlay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoPlay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_play.GoPlay",
	HandlerType: (*GoPlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResponse",
			Handler:    _GoPlay_GetResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
